services:
  data:
    image: autoeh-data:local
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: autoeh-data
    env_file:
      - data/.env
    command: ["help"]
    volumes:
      - ./data/runtime:/app/runtime
    restart: "no"

  data-ui:
    image: autoeh-data:local
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: autoeh-data-ui
    env_file:
      - data/.env
    command: ["data-ui"]
    ports:
      - "8501:8501"
    volumes:
      - ./data/runtime:/app/runtime
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
