---
services:
  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    ports:
      - "3000:3000"
    volumes:
      - [YOUR_CONTENT_DIRECTORY]:/home/koyomi/lanraragi/content
      - [YOUR_THUMBNAIL_DIRECTORY]:/home/koyomi/lanraragi/thumb
      - [YOUR_DATABASE_DIRECTORY]:/home/koyomi/lanraragi/database
    restart: unless-stopped