services:
  data-ui:
    image: jbking114514/autoehhunter:latest
    container_name: autoehhunter
    command: ["data-ui"]
    ports:
      - "8501:8501"
    volumes:
      - ./runtime:/app/runtime
    restart: unless-stopped
